### PR TITLE
Adding support for custom/different word lists per generate request.

### PR DESCRIPTION
**Pull request by jbueler**

### CODE REVIEW

**Comment by stevearoonie** [comment]
I was about to do something similar. This would be good to have in.

**Comment by vot** [comment]
Hi @jbueler and @stevearoonie,

I'm going to merge this into a separate branch and make a couple of small changes there.
Just a tiny coding convention adjustment I mentioned in PR review and will see if I can expose it in a sensible way through CLI.

This will likely be published on npm in a couple of days.

**Comment by vot** [comment]
@jbueler, @stevearoonie:

You can see the updates here:
https://github.com/vot/xkpasswd-node/compare/custom-word-list
It's still quick and dirty so will need a cleanup and some tests to cover this new functionality.

Anyway this will allow the `wordList` option to be specified through CLI or programmatically as:
- JSON file
- text file
- an array of strings
- a string with individual words separated by commas

In addition the list will be cleaned up on the fly to ensure no spaces are introduced as well as remove empty strings.

Thanks for providing the base for this work @jbueler, much appreciated.
Hopefully this will cover all typical scenarios.

**Comment by stevearoonie** [comment]
Thanks a lot @vot and @jbueler. I appreciate your work.

**Comment by jbueler** [comment]
Hey this is great, thanks for incorporating this feature. You did a much better job, more thought out. Thanks for your work on this module!

**Pull request merged**
